Fix QueryDatabaseMetaDataIT
FAILURE! - in org.apache.phoenix.end2end.QueryDatabaseMetaDataIT
testCreateOnExistingTable(org.apache.phoenix.end2end.QueryDatabaseMetaDataIT)  Time elapsed: 9.415 sec  <<< FAILURE!
java.lang.AssertionError: expected:<FALSE> but was:<false>
	at org.apache.phoenix.end2end.QueryDatabaseMetaDataIT.testCreateOnExistingTable(QueryDatabaseMetaDataIT.java:620)

(cherry picked from commit 1c0c7e756d08cfce6cccad9b9813229a366488b4)

Reason: compat
Author: Andrew Purtell
Repo: https://github.com/chiastic-security/phoenix-for-cloudera/
Ref: CDH-36667